project_id = "djmfvdxfqohwvrtvnbsp"

[functions.generate-question]
verify_jwt = false

[functions.evaluate-answer]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.speech-to-text]
verify_jwt = false
